const fs = require('fs');

let content = fs.readFileSync('./src/data/themes.js', 'utf8');

const specificPositions = {
  'Ronaldo Nazário': 'Buteur',
  'Marco van Basten': 'Buteur',
  'Robert Lewandowski': 'Buteur',
  'Karim Benzema': 'Buteur',
  'Zlatan Ibrahimović': 'Buteur',
  'Luis Suárez': 'Buteur',
  'Erling Haaland': 'Buteur',
  'Gabriel Batistuta': 'Buteur',
  'Romário': 'Buteur',
  'Gerd Müller': 'Buteur',
  'Alan Shearer': 'Buteur',
  'Sergio Agüero': 'Buteur',
  'Didier Drogba': 'Buteur',
  "Samuel Eto'o": 'Buteur',
  'Andriy Shevchenko': 'Buteur',
  'Ruud van Nistelrooy': 'Buteur',
  'Harry Kane': 'Buteur',
  'Nicklas "Lord" Bendtner': 'Buteur',
  'Eric M. Choupo-Moting': 'Buteur',
  'Martin Braithwaite': 'Buteur',
  'Marouane Chamakh': 'Buteur',
  'Kostas Mitroglou': 'Buteur',
  'Yaya Sanogo': 'Buteur',
  'Andy Carroll': 'Buteur',
  'Valeri Bojinov': 'Buteur',

  'Lionel Messi': 'Ailier Droit',
  'Cristiano Ronaldo': 'Ailier Gauche',
  'Pelé': 'Faux 9',
  'Diego Maradona': 'Milieu Offensif',
  'Johan Cruyff': 'Faux 9',
  'Ronaldinho': 'Ailier Gauche',
  'Thierry Henry': 'Ailier Gauche',
  'Neymar Jr': 'Ailier Gauche',
  'Kylian Mbappé': 'Ailier Gauche',
  'Garrincha': 'Ailier Droit',
  'George Best': 'Ailier Droit',
  'Rivaldo': 'Ailier Gauche',
  'Luis Figo': 'Ailier Droit',
  'Gareth Bale': 'Ailier Droit',
  'Arjen Robben': 'Ailier Droit',
  'Franck Ribéry': 'Ailier Gauche',
  'Wayne Rooney': 'Second Attaquant',
  'Antony (Spin Master)': 'Ailier Droit',
  'Jesé Rodríguez': 'Ailier Gauche',
  'Gervinho': 'Ailier Droit',
  'Valère Germain': 'Second Attaquant',
  'Clinton Njie': 'Ailier Droit',
  'Bebé': 'Ailier',
  'Gabriel Obertan': 'Ailier',
  'Jesper Blomqvist': 'Ailier Gauche',

  'Zinedine Zidane': 'Milieu Offensif',
  'Andrés Iniesta': 'Milieu Central',
  'Xavi Hernández': 'Milieu Central',
  'Luka Modrić': 'Milieu Central',
  'Michel Platini': 'Milieu Offensif',
  'Lothar Matthäus': 'Milieu Défensif',
  'Andrea Pirlo': 'Milieu Récupérateur',
  'Paul Scholes': 'Milieu Central',
  'Steven Gerrard': 'Milieu Central',
  'Frank Lampard': 'Milieu Central',
  'Kevin De Bruyne': 'Milieu Offensif',
  'Toni Kroos': 'Milieu Central',
  'Sergio Busquets': 'Milieu Défensif',
  'Clarence Seedorf': 'Milieu Central',
  'Ruud Gullit': 'Milieu Central',
  'Patrick Vieira': 'Milieu Défensif',
  'Roy Keane': 'Milieu Défensif',
  'Joey Barton': 'Milieu Défensif',
  'Marouane Fellaini': 'Milieu Central',
  'Grzegorz Krychowiak': 'Milieu Défensif',
  'Abou Diaby (Blessé)': 'Milieu Central',
  'Fred': 'Milieu Défensif',
  'Ali Dia': 'Milieu Central',
  'Eric Djemba-Djemba': 'Milieu Défensif',
  "Yann M'Vila": 'Milieu Défensif',

  'Paolo Maldini': 'Défenseur Central',
  'Franz Beckenbauer': 'Défenseur Central',
  'Franco Baresi': 'Défenseur Central',
  'Sergio Ramos': 'Défenseur Central',
  'Fabio Cannavaro': 'Défenseur Central',
  'Alessandro Nesta': 'Défenseur Central',
  'Carles Puyol': 'Défenseur Central',
  'John Terry': 'Défenseur Central',
  'Rio Ferdinand': 'Défenseur Central',
  'Nemanja Vidić': 'Défenseur Central',
  'Gerard Piqué': 'Défenseur Central',
  'Virgil van Dijk': 'Défenseur Central',
  'Thiago Silva': 'Défenseur Central',
  'Giorgio Chiellini': 'Défenseur Central',
  'Laurent Blanc': 'Défenseur Central',
  'Marcel Desailly': 'Défenseur Central',
  'Vincent Kompany': 'Défenseur Central',
  'Harry Maguire': 'Défenseur Central',
  'Phil Jones': 'Défenseur Central',
  'Shkodran Mustafi': 'Défenseur Central',
  'Titus Bramble': 'Défenseur Central',
  'Djimi Traoré': 'Défenseur Central',
  'Philippe Senderos': 'Défenseur Central',
  'Jean-Alain Boumsong': 'Défenseur Central',
  'Sébastien Squillaci': 'Défenseur Central',

  'Roberto Carlos': 'Latéral Gauche',
  'Cafu': 'Latéral Droit',
  'Dani Alves': 'Latéral Droit',
  'Philipp Lahm': 'Latéral Droit',
  'Marcelo': 'Latéral Gauche',
  'Javier Zanetti': 'Latéral Droit',
  'Ashley Cole': 'Latéral Gauche',
  'Lilian Thuram': 'Latéral Droit',
  'Maicon': 'Latéral Droit',
  'Jordi Alba': 'Latéral Gauche',
  'Trent Alexander-Arnold': 'Latéral Droit',
  'Andy Robertson': 'Latéral Gauche',
  'Kyle Walker': 'Latéral Droit',
  'Gianluca Zambrotta': 'Latéral Gauche',
  'Bixente Lizarazu': 'Latéral Gauche',
  'Patrice Evra': 'Latéral Gauche',
  'Branislav Ivanović': 'Latéral Droit',
  'Bouna Sarr': 'Latéral Droit',
  'Layvin Kurzawa': 'Latéral Gauche',
  'Aly Cissokho': 'Latéral Gauche',
  'Julien Faubert': 'Latéral Droit',
  'Carl Jenkinson': 'Latéral Droit',
  'André Santos': 'Latéral Gauche',
  'Cristian Zaccardo': 'Latéral Droit',
  'Kévin Constant': 'Latéral Gauche',

  'Lev Yashin': 'Gardien de But',
  'Gianluigi Buffon': 'Gardien de But',
  'Iker Casillas': 'Gardien de But',
  'Manuel Neuer': 'Gardien de But',
  'Peter Schmeichel': 'Gardien de But',
  'Oliver Kahn': 'Gardien de But',
  'Edwin van der Sar': 'Gardien de But',
  'Petr Čech': 'Gardien de But',
  'Dida': 'Gardien de But',
  'Júlio César': 'Gardien de But',
  'Thibaut Courtois': 'Gardien de But',
  'Alisson Becker': 'Gardien de But',
  'Ederson': 'Gardien de But',
  'Hugo Lloris': 'Gardien de But',
  'Fabien Barthez': 'Gardien de But',
  'Gordon Banks': 'Gardien de But',
  'Dino Zoff': 'Gardien de But',
  'Loris Karius': 'Gardien de But',
  'Kepa Arrizabalaga': 'Gardien de But',
  'Apoula Edel': 'Gardien de But',
  'Ciprian Tătărușanu': 'Gardien de But',
  'Ali Ahamada': 'Gardien de But',
  'Massimo Taibi': 'Gardien de But',
  'Richard Wright': 'Gardien de But',
  'Rúnar Alex Rúnarsson': 'Gardien de But'
};

let newContent = content.replace(/\{ name: '([^']+)', rating: (\d+)(, isTroll: true)? \}/g, (match, name, rating, isTroll) => {
  const pos = specificPositions[name];
  if (pos) {
    if (isTroll) {
      return `{ name: '${name}', specificPosition: '${pos}', rating: ${rating}, isTroll: true }`;
    }
    return `{ name: '${name}', specificPosition: '${pos}', rating: ${rating} }`;
  }
  return match;
});

// Write it back
fs.writeFileSync('./src/data/themes.js', newContent, 'utf8');
console.log('themes.js updated successfully!');
