const fs = require('fs');

let content = fs.readFileSync('./src/data/themes.js', 'utf8');

const specificPositions = {
  'Ronaldo Nazário': 'Buteur (9)',
  'Marco van Basten': 'Buteur (9)',
  'Robert Lewandowski': 'Buteur (9)',
  'Karim Benzema': 'Buteur (9)',
  'Zlatan Ibrahimović': 'Buteur (9)',
  'Luis Suárez': 'Buteur (9)',
  'Erling Haaland': 'Buteur (9)',
  'Gabriel Batistuta': 'Buteur (9)',
  'Romário': 'Buteur (9)',
  'Gerd Müller': 'Buteur (9)',
  'Alan Shearer': 'Buteur (9)',
  'Sergio Agüero': 'Buteur (9)',
  'Didier Drogba': 'Buteur (9)',
  'Samuel Eto\\'o': 'Buteur (9)',
  'Andriy Shevchenko': 'Buteur (9)',
  'Ruud van Nistelrooy': 'Buteur (9)',
  'Harry Kane': 'Buteur (9)',
  'Nicklas "Lord" Bendtner': 'Buteur (9)',
  'Eric M. Choupo-Moting': 'Buteur (9)',
  'Martin Braithwaite': 'Buteur (9)',
  'Marouane Chamakh': 'Buteur (9)',
  'Kostas Mitroglou': 'Buteur (9)',
  'Yaya Sanogo': 'Buteur (9)',
  'Andy Carroll': 'Buteur (9)',
  'Valeri Bojinov': 'Buteur (9)',

  'Lionel Messi': 'Ailier Droit',
  'Cristiano Ronaldo': 'Ailier Gauche',
  'Pelé': 'Faux 9',
  'Diego Maradona': 'Milieu Offensif',
  'Johan Cruyff': 'Faux 9',
  'Ronaldinho': 'Ailier Gauche',
  'Thierry Henry': 'Ailier Gauche',
  'Neymar Jr': 'Ailier Gauche',
  'Kylian Mbappé': 'Ailier Gauche',
  'Garrincha': 'Ailier Droit',
  'George Best': 'Ailier Droit',
  'Rivaldo': 'Ailier Gauche',
  'Luis Figo': 'Ailier Droit',
  'Gareth Bale': 'Ailier Droit',
  'Arjen Robben': 'Ailier Droit',
  'Franck Ribéry': 'Ailier Gauche',
  'Wayne Rooney': 'Second Attaquant',
  'Antony (Spin Master)': 'Ailier Droit',
  'Jesé Rodríguez': 'Ailier Gauche',
  'Gervinho': 'Ailier Droit',
  'Valère Germain': 'Second Attaquant',
  'Clinton Njie': 'Ailier Droit',
  'Bebé': 'Ailier',
  'Gabriel Obertan': 'Ailier',
  'Jesper Blomqvist': 'Ailier Gauche',

  'Zinedine Zidane': 'Milieu Offensif (10)',
  'Andrés Iniesta': 'Milieu Central (8)',
  'Xavi Hernández': 'Milieu Central (8)',
  'Luka Modrić': 'Milieu Central (8)',
  'Michel Platini': 'Milieu Offensif (10)',
  'Lothar Matthäus': 'Milieu Défensif (6)',
  'Andrea Pirlo': 'Milieu Récupérateur (6)',
  'Paul Scholes': 'Milieu Central (8)',
  'Steven Gerrard': 'Milieu Central (8)',
  'Frank Lampard': 'Milieu Central (8)',
  'Kevin De Bruyne': 'Milieu Offensif (10)',
  'Toni Kroos': 'Milieu Central (8)',
  'Sergio Busquets': 'Milieu Défensif (6)',
  'Clarence Seedorf': 'Milieu Central (8)',
  'Ruud Gullit': 'Milieu Central (8)',
  'Patrick Vieira': 'Milieu Défensif (6)',
  'Roy Keane': 'Milieu Défensif (6)',
  'Joey Barton': 'Milieu Défensif (6)',
  'Marouane Fellaini': 'Milieu Central (8)',
  'Grzegorz Krychowiak': 'Milieu Défensif (6)',
  'Abou Diaby (Blessé)': 'Milieu Central (8)',
  'Fred': 'Milieu Défensif (6)',
  'Ali Dia': 'Milieu Central',
  'Eric Djemba-Djemba': 'Milieu Défensif (6)',
  'Yann M\\'Vila': 'Milieu Défensif (6)',

  'Paolo Maldini': 'Défenseur Central',
  'Franz Beckenbauer': 'Défenseur Central',
  'Franco Baresi': 'Défenseur Central',
  'Sergio Ramos': 'Défenseur Central',
  'Fabio Cannavaro': 'Défenseur Central',
  'Alessandro Nesta': 'Défenseur Central',
  'Carles Puyol': 'Défenseur Central',
  'John Terry': 'Défenseur Central',
  'Rio Ferdinand': 'Défenseur Central',
  'Nemanja Vidić': 'Défenseur Central',
  'Gerard Piqué': 'Défenseur Central',
  'Virgil van Dijk': 'Défenseur Central',
  'Thiago Silva': 'Défenseur Central',
  'Giorgio Chiellini': 'Défenseur Central',
  'Laurent Blanc': 'Défenseur Central',
  'Marcel Desailly': 'Défenseur Central',
  'Vincent Kompany': 'Défenseur Central',
  'Harry Maguire': 'Défenseur Central',
  'Phil Jones': 'Défenseur Central',
  'Shkodran Mustafi': 'Défenseur Central',
  'Titus Bramble': 'Défenseur Central',
  'Djimi Traoré': 'Défenseur Central',
  'Philippe Senderos': 'Défenseur Central',
  'Jean-Alain Boumsong': 'Défenseur Central',
  'Sébastien Squillaci': 'Défenseur Central',

  'Roberto Carlos': 'Latéral Gauche',
  'Cafu': 'Latéral Droit',
  'Dani Alves': 'Latéral Droit',
  'Philipp Lahm': 'Latéral Droit',
  'Marcelo': 'Latéral Gauche',
  'Javier Zanetti': 'Latéral Droit',
  'Ashley Cole': 'Latéral Gauche',
  'Lilian Thuram': 'Latéral Droit',
  'Maicon': 'Latéral Droit',
  'Jordi Alba': 'Latéral Gauche',
  'Trent Alexander-Arnold': 'Latéral Droit',
  'Andy Robertson': 'Latéral Gauche',
  'Kyle Walker': 'Latéral Droit',
  'Gianluca Zambrotta': 'Latéral Gauche',
  'Bixente Lizarazu': 'Latéral Gauche',
  'Patrice Evra': 'Latéral Gauche',
  'Branislav Ivanović': 'Latéral Droit',
  'Bouna Sarr': 'Latéral Droit',
  'Layvin Kurzawa': 'Latéral Gauche',
  'Aly Cissokho': 'Latéral Gauche',
  'Julien Faubert': 'Latéral Droit',
  'Carl Jenkinson': 'Latéral Droit',
  'André Santos': 'Latéral Gauche',
  'Cristian Zaccardo': 'Latéral Droit',
  'Kévin Constant': 'Latéral Gauche',

  'Lev Yashin': 'Gardien de But',
  'Gianluigi Buffon': 'Gardien de But',
  'Iker Casillas': 'Gardien de But',
  'Manuel Neuer': 'Gardien de But',
  'Peter Schmeichel': 'Gardien de But',
  'Oliver Kahn': 'Gardien de But',
  'Edwin van der Sar': 'Gardien de But',
  'Petr Čech': 'Gardien de But',
  'Dida': 'Gardien de But',
  'Júlio César': 'Gardien de But',
  'Thibaut Courtois': 'Gardien de But',
  'Alisson Becker': 'Gardien de But',
  'Ederson': 'Gardien de But',
  'Hugo Lloris': 'Gardien de But',
  'Fabien Barthez': 'Gardien de But',
  'Gordon Banks': 'Gardien de But',
  'Dino Zoff': 'Gardien de But',
  'Loris Karius': 'Gardien de But',
  'Kepa Arrizabalaga': 'Gardien de But',
  'Apoula Edel': 'Gardien de But',
  'Ciprian Tătărușanu': 'Gardien de But',
  'Ali Ahamada': 'Gardien de But',
  'Massimo Taibi': 'Gardien de But',
  'Richard Wright': 'Gardien de But',
  'Rúnar Alex Rúnarsson': 'Gardien de But'
};

let newContent = content.replace(/\{ name: '([^']+)', rating: (\d+)(, isTroll: true)? \}/g, (match, name, rating, isTroll) => {
  const pos = specificPositions[name];
  if (pos) {
    if (isTroll) {
      return \`{ name: '\${name}', specificPosition: '\${pos}', rating: \${rating}, isTroll: true }\`;
    }
    return \`{ name: '\${name}', specificPosition: '\${pos}', rating: \${rating} }\`;
  }
  return match;
});

fs.writeFileSync('./src/data/themes.js', newContent, 'utf8');
console.log('themes.js updated successfully!');
